### ISSUE TITLE
add some tags to be searchable

### ISSUE THREAD

**Issue by JotaPe** [awolven/VkTk#1]
So I had a problem to find this library, that is not abandoned about Vulkan and Common Lisp, will be nice if you add some tags like "common-lisp" "vulkan" and "graphics" to be searchable on Github, is a very nice library that more people need to know and I only find it because of one Reddit post that you probably made, so yeah, will be very nice to add some tags.

If you search "cl vulkan" or "common lisp vulkan" your library not even show up.

**Comment by awolven** [comment]
Thanks for the tip.  I added some tags.
