### ISSUE TITLE
The alien function "igGetPlatformIO" is undefined.

### ISSUE THREAD

**Issue by ebrasca** [awolven/VkTk#2]
When I run the example app I get:
The alien function "igGetPlatformIO" is undefined.

Thank you!

**Comment by awolven** [comment]
What platform are you on?

**Comment by ebrasca** [comment]
I am using Gentoo GNU/Linux!

**Comment by awolven** [comment]
I need to rebuild my linux environment, this could take a while.

In the meantime, I should check, are you sure you're loading cimgui.so?
Generally the error message you're seeing is when the lisp code is loaded
but the shared object is not.

AKW

**Comment by ebrasca** [comment]
I think it did load! How I can check?

**Comment by awolven** [comment]
(cffi:list-foreign-libraries)

**Comment by awolven** [comment]
I pushed a new cimgui.so with the missing change to vktk, so you can pull and it should work now.

**Comment by ebrasca** [comment]
Thanks the example now does start!
